/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhh_jiagu_nativelib_AESUtil */

#ifndef _Included_com_zhh_jiagu_shell_util_AESUtil
#define _Included_com_zhh_jiagu_shell_util_AESUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhh_jiagu_nativelib_AESUtil
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zhh_jiagu_shell_util_AESUtil_encrypt
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_zhh_jiagu_nativelib_AESUtil
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zhh_jiagu_shell_util_AESUtil_decrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
